export { default as Account } from './Account';
export { default as Dashboard } from './Dashboard';
export { default as Icons } from './Icons';
export { default as NotFound } from './NotFound';
export { default as ProductList } from './ProductList';
export { default as ViewProduct } from './ViewProduct';
export { default as SignIn } from './SignIn';
export { default as SignUp } from './SignUp';
export { default as Retailer } from './Retailer';
export { default as AddProduct } from './AddProduct';
// export { default as UserList } from './UserList';
